# Configuration file for the project

# Root directory for storing data
artifacts_root: artifacts

# Configuration for data ingestion
data_ingestion:
  # Root directory for data ingestion
  root_dir: artifacts/data_ingestion
  # URL to download the data from
  source_URL: https://drive.google.com/file/d/1e9oof67nDls9kd6CRzhJvk8Le3WmIh5y/view?usp=sharing
  # Local file path where the downloaded data will be stored
  local_data_file: artifacts/data_ingestion/data.zip
  # Directory where the downloaded data will be extracted
  unzip_dir: artifacts/data_ingestion

# Configuration for preparing the base model
prepare_base_model:
  # Root directory for preparing the base model
  root_dir: artifacts/prepare_base_model
  # File path to the base model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  # File path to the updated base model
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  # Root directory for training artifacts
  root_dir: artifacts/training
  # Path to save the trained model
  trained_model_path: artifacts/training/model.h5


