# Use the official Python 3.8 slim buster image as base
FROM python:3.8-slim-buster

# Update package lists and install AWS CLI #app will be deployed on AWS cli
RUN apt update -y && apt install awscli -y 

# Set the working directory for the container 
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Python dependencies from requirements.txt
RUN pip install -r requirements.txt

# Command to run the Python application when the container starts
CMD ["python3", "app.py"]
